name: go-ci

on: [push]

jobs:
  # 共通処理
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: check out
        uses: actions/checkout@v2

      - name: package install
        run: go mod tidy

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Test code
        run: go test -v ./...
